version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: |
          python3 main.py
          ls

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install pytest --user
      - run: python3 test_main.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
